global: &global
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  host: localhost

development:
  database: mc_normal_mode_development
  <<: *global

test: &test
  database: mc_normal_mode_test
  <<: *global

production:
  database: mc_normal_mode

cucumber:
  <<: *test
