# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3f2247262527d139d2ac870ca3ae165152520fb5f13770ba3959d755aaa785ddfc9e6ece6de433b7ae1531f3edacd2384a78c95c1fbb09717d76ca70c78a864

test:
  secret_key_base: eee45cf881d87565f79e3ccccf7c959803de573d20ecd02dec608abede0d2739c3422442aaba0b759529e9f8ddca4bbff54d7558e59ecc16d24135c9c1a3b75d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
